### ISSUE TITLE
How do I use a saved model to predict?

### ISSUE THREAD

**Issue by nvlong198** [Niger-Volta-LTI/yoruba-adr#7]
Hi team, how I can predict a sentence with models in /models? 
Do you have any suggestion?
thank for your support.

**Comment by ruohoruotsi** [comment]
Great question! Once you have a model, you can predict with a script like such (from an older version of OpenNMT-py). I'll put together and verify a working prediction script for the current codebase!

```
#!/usr/bin/env bash

echo "[INFO] running inference on dev sources"

export MODEL_DIR=./seq2seq/
export PRED_DIR=${MODEL_DIR}/pred
export DEV_SOURCES=./dev/sources.txt
mkdir -p ${PRED_DIR}

python3.5 -m seq2seq.bin.infer \
  --tasks "
    - class: DecodeText" \
  --model_dir $MODEL_DIR \
  --input_pipeline "
    class: ParallelTextInputPipeline
    params:
      source_files:
        - $DEV_SOURCES" > ${PRED_DIR}/predictions.txt
```

**Comment by ruohoruotsi** [comment]
Great question! Once you have a model, you can predict using `translate.py` (top level of OpenNMT-py). I'll put together and verify a working prediction script now

**Comment by ruohoruotsi** [comment]
I added an example here: https://github.com/Niger-Volta-LTI/yoruba-adr/blob/master/02_run_prediction.sh. it takes a checkpoint model (.pt file), a test text file of utterances to translate/ADR and `pred.txt` file to write and it does the predictions.

**Comment by ruohoruotsi** [comment]
With https://github.com/Niger-Volta-LTI/yoruba-adr/commit/0bb7e1c9668f6d6b0e778b0ad5a3fb62bbbe9dad using a very early (barely trained) model, this is what the results look like:

```
$ ./02_run_prediction.sh
[INFO] running inference on test sources
python3.6/site-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.3 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
[2019-02-23 02:07:14,406 INFO] Translating shard 0.

SENT 1: ['fa', 'oko', 'riro', 'ile', 'didagbe']
PRED 1: orí orí òní ilẹ̀ wíwọ̀
PRED SCORE: -21.0413

SENT 2: ['ara', 'abuda', 're', 'kuku', 'wa']
PRED 2: inú ọ̀dọ̀ rẹ̀ dára wá
PRED SCORE: -12.5837

SENT 3: ['akekoo', 'pelu', 'okan', 'miiran', 'laarin']
PRED 3: ọ̀kan pẹ̀lú ọkàn mìíràn láàrin
PRED SCORE: -9.3838

SENT 4: ['lori', 'inawo', 'kinaawo', 'yoo', 'je']
PRED 4: lórí lára ìpèsè yóò jẹ́
PRED SCORE: -13.6298
...
```

**Comment by nvlong198** [comment]
@ruohoruotsi 
Can I predict more quickly? I've predicted about 900000 sentences and it takes up to 1 day with XeonE3 24 core - 48 threads :(

[2019-02-28 13:06:46,285 INFO] Translating shard 0.
.
...
[2019-03-01 10:24:16,705 INFO] Translating shard 89.

**Comment by ruohoruotsi** [comment]
Hi @nvlong198 I think this maybe a question for the owners of the OpenNMT-py, upon which this code is based: https://github.com/OpenNMT/OpenNMT-py, they may have some optimization tricks to suggest

Alternatively you could
(1) profiling the code and see where it is taking time, perhaps you can suggest some improvements.

(2) try beam search, which a smaller beam width (that may sacrifice accuracy) but you'll be able to decode/translate much faster
