### ISSUE TITLE
Can I train a model with larger text corpus ?

### ISSUE THREAD

**Issue by nvlong198** [Niger-Volta-LTI/yoruba-adr#8]
I have trained with 8 million sentences. and it works well 
But with larger corpus (more than 5 times) I have a problem with memory, How to deal with it? Which parameter I have to change?
I use Tesla K40m with 12GiB memory.
Thank you ;) .
![image](https://user-images.githubusercontent.com/23328191/53295856-f5847980-3836-11e9-9b0c-2c42459f4a42.png)

**Comment by ruohoruotsi** [comment]
@nvlong198 Are you training Vietnamese? If so welcome from a fellow hard diacritic language! If you're training Yorùbá, please share your 8 million sentences!!

To answer your question, with a larger corpus on a single GPU,  for each step the GPU memory is filled with the data from a minibatchs, so I would recommend reducing the minibatch-size argument to train.py (`-batch_size 256`). With a smaller mini batch-size, the number of total training steps will increase but they should all fit into memory more comfortably. See: https://github.com/OpenNMT/OpenNMT-py/issues/301#issuecomment-358445798

Also note that I'm using OpenNMT-py and others have reported similar issues, perhaps have a read/browse through some of those issues

- https://github.com/OpenNMT/OpenNMT-py/pull/481
- https://github.com/OpenNMT/OpenNMT-py/issues/301
- https://github.com/OpenNMT/OpenNMT-py/issues/476
- https://github.com/OpenNMT/OpenNMT-py/pull/499

**Comment by nvlong198** [comment]
@ruohoruotsi  Yes, Vietnamese!
I'll do what you suggested. Thanks for your advice ;)

**Comment by ruohoruotsi** [comment]
So you're now training on a corpus of 40+ Million sentences? Let us know if the suggestion works or what you end up doing as final solution.

**Comment by nvlong198** [comment]
I tried with _-batch_size 16_ , but it still not work :(

**Comment by ruohoruotsi** [comment]
Can you please paste your full training command as well as the outputlog (including the error message)?

**Comment by nvlong198** [comment]
```
python ./src/train.py -batch_size 16 -gpuid 0 -world_size 1 -gpu_ranks 0 \
    -data data/demo \
    -...
```
and I dismiss  these code in src/train.py to be able to run.
```
# if opt.gpuid:
#     raise AssertionError("gpuid is 
#       see world_size and gpu_ranks")

```

**Comment by ruohoruotsi** [comment]
Can you please show me some of the output before the OOM error? Does it happen on around the same time-step each time?

**Comment by nvlong198** [comment]
`[2019-02-26 15:06:57,995 INFO] Step 9950/100000; acc:  79.26; ppl:  2.36; xent: 0.86; lr: 0.00100; 1506/1631 tok/s;    648 sec`
`[2019-02-26 15:07:00,987 INFO] Step 10000/100000; acc:  78.72; ppl:  2.51; xent: 0.92; lr: 0.00100; 1339/1473 tok/s;    651 sec`
`[2019-02-26 15:07:26,724 INFO] Loading dataset from data/demo.valid.0.pt, number of examples: 1000000`
`Traceback (most recent call last):`
`  File "./src/train.py", line 123, in <module>`
`    main(opt)`
`  File "./src/train.py", line 54, in main`
`    single_main(opt, 0)`
`  File "/home/trienpm/vnlong/yoruba-adr/src/onmt/train_single.py", line 151, in main`
`    trainer.train(train_iter, valid_iter, opt.train_steps, opt.valid_steps)`
`  File "/home/trienpm/vnlong/yoruba-adr/src/onmt/trainer.py", line 186, in train`
`    valid_stats = self.validate(valid_iter)`
`  File "/home/trienpm/vnlong/yoruba-adr/src/onmt/trainer.py", line 229, in validate`
`    _, batch_stats = self.valid_loss(batch, outputs, attns)`
`  File "/home/trienpm/vnlong/yoruba-adr/src/onmt/utils/loss.py", line 157, in __call__`
`    loss, stats = self._compute_loss(batch, **shard)`
`  File "/home/trienpm/vnlong/yoruba-adr/src/onmt/utils/loss.py", line 233, in _compute_loss`
`    scores = self.generator(bottled_output)`
`  File "/home/trienpm/miniconda3/envs/vnlong/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__`
`    result = self.forward(*input, **kwargs)`
`  File "/home/trienpm/miniconda3/envs/vnlong/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward`
`    input = module(input)`
`  File "/home/trienpm/miniconda3/envs/vnlong/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__`
`    result = self.forward(*input, **kwargs)`
`  File "/home/trienpm/miniconda3/envs/vnlong/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 936, in forward`
`    return F.log_softmax(input, self.dim, _stacklevel=5)`
`  File "/home/trienpm/miniconda3/envs/vnlong/lib/python3.6/site-packages/torch/nn/functional.py", line 1295, in log_softmax`
`    ret = input.log_softmax(dim)`
`RuntimeError: CUDA out of memory. Tried to allocate 6.07 GiB (GPU 0; 11.92 GiB total capacity; 7.06 GiB already allocated; 2.59 GiB free; 1.92 GiB cached)`
`

**Comment by nvlong198** [comment]
@ruohoruotsi I think the problem in **Loading datasets**, with small data, only have 1 valid.pt file
OOM error when it having more valid.pt file :(

**Comment by nvlong198** [comment]
I change **valid_steps** and **size** of the validation, and it works well
Thank you

**Comment by ruohoruotsi** [comment]
Okay, great! so can you please put share your updated command or diffs. So number of validation sets and size of the RNN helped you? Cheers!

**Comment by ruohoruotsi** [comment]
Also if you feel like some of your changes and defaults are better for everyone. Please submit a Pull-Request (PR). Cảm ơn bạn!

**Comment by nvlong198** [comment]
In my corpus, quick solution are changed **-train_steps** to **1000000** and ignore **valid_steps** (valid_steps to 1000000)
Is the probem is valid_batch_size ?

**Comment by ruohoruotsi** [comment]
Okay, let me see if I understand: You were getting OOM from frequent validation every X training steps running your GPU out of memory? so you changed the defaults defined in `src/onmt/opts.py` to 

1. Train longer &rarr; 1e6 steps 
2. stop doing validation by setting the ***valid_steps*** to be as big as number of ***train_steps*** so only doing validation once AT THE END of training?  Is this correct and working?

`    group.add('--valid_steps', '-valid_steps', type=int, default=10000,
help='Perfom validation every X steps')`

`    group.add('--train_steps', '-train_steps', type=int, default=100000,
help='Number of training steps')`

I think if you're not doing validation until the END of training, then ***valid_batch_size*** shouldn't matter:

`    group.add('--valid_batch_size', '-valid_batch_size', type=int, default=32,
help='Maximum batch size for validation')`

**Comment by ruohoruotsi** [comment]
@nvlong198 Please if you use this code in your research or publications please cite:
```
@article{orife2018attentive,
  title={Attentive Sequence-to-Sequence Learning for Diacritic Restoration of Yor{\`u}B{\'a} Language Text},
  author={Orife, Iroro},
  journal={Proc. Interspeech 2018},
  pages={2848--2852},
  year={2018}
}
```
